version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: codesafe
      MYSQL_DATABASE: db_safexpress
      MYSQL_USER: root
      MYSQL_PASSWORD: codesafe
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ''
    ports:
      - "8080:80"
    depends_on:
      - mysql
