version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: codesafe
      MYSQL_DATABASE: db_safexpress
      MYSQL_USER: root
      MYSQL_PASSWORD: codesafe
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
