version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: c0deSafe
      MYSQL_DATABASE: db_safexpress
      MYSQL_USER: root
      MYSQL_PASSWORD: c0deSafe
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ''
    ports:
      - "9002:80"
    depends_on:
      - mysql

volumes:
  mysql-data:
