version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: c0deSafe
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1 
    ports:
      - "8080:80"

