version: '3.8'

services:
  db:
    image: mysql
    restart: always
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: codesafe
      MYSQL_DATABASE: db_safexpress
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
