version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: db_safexpress
      MYSQL_USER: app
      MYSQL_PASSWORD: c0deSafe
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: app
      PMA_PASSWORD: c0deSafe
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:

