version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: c0deSafe
      MYSQL_DATABASE: db_safexpress
      MYSQL_USER: app
      MYSQL_PASSWORD: C0deSafe
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin:latest
      ports:
        - 9002:80
      environment:
        - PMA_ARBITRARY=1
volumes:
  mysql-data:
